apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: abdulwahabmsalih/backenduser:latest
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_HOST
          value: postgres.node-app.svc.cluster.local
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: pg-secrets
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pg-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secrets
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: node-app
spec:
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000